version: '3'

services:
  api:
    build: ./api
    ports:
      - "5000:5000"
    environment:
      - REDIS_URL=redis://redis:6379
    networks:
      - app-network
    depends_on:
      - web

  web:
    build: ./web
    ports:
      - "80:80"
    networks:
      - app-network

  redis:
    image: redis
    networks:
      - app-network

networks:
  app-network: