version: '3'

services:
  api:
    build: ./api
    ports:
      - "5000:5000"
    environment:
      - REDIS_URL=redis://redis:6379
    networks:
      - dsn-03-red  # Nombre específico para la red de la API

  react:
    build: ./react-front
    ports:
      - "80:80"
    networks:
      - dsn-03-red  # Usa el mismo nombre de red que la API

  redis:
    image: redis

networks:
  dsn-03-red:
    driver: bridge
